Consolidate roles.
ndlib/aleph-gateway-blueprints pull request #5
Opened 2021-04-01 19:11 UTC by mlkirkpatrick

Ya know so we can use one role instead of 8... :)

2021-04-01 19:13 UTC, rdoughty approved these changes
nice

2021-04-01 19:43 UTC, ialford requested changes
I struggle with breaking this up (and the permissions on the Lambdas in general). If we consolidate the roles, the only advantage I see is role count for each service is decreased. However, we may lose traceability when it comes to "which lambda did some operation" when there's only one role shared between all of them. Could you tell me if there's more to gain from your perspective?

That takes me to the bigger concern, which is the blast radius of the Lambda permissions as it exists here: these lambdas *could* delete network interfaces for things unrelated to the lambdas themselves, including potentially for our EC2 instances which would be a major point of failure.

Could we namespace the policies at least, similar to [MARBLE](https://github.com/ndlib/marble-blueprints/blob/master/deploy/cdk/lib/namespaced-policy.ts#L98-L108) since it seems like it could be an option once we know what the prefixes may be, per the [AWS Docs](https://docs.amazonaws.cn/en_us/service-authorization/latest/reference/list_amazonec2.html).

2021-04-01 21:08 UTC, mlkirkpatrick commented
My goal was just to reduce the number of roles since we are at the 1000 limit in testlibnd. I'm sure we can request an increase, but I wanted to see if there was anything I could do to be more efficient while we're at it, and I noticed that cdk applications in particular were creating a huge number of roles.

Each lambda is going to create its own log group regardless, so I don't see that being an issue, but If a lambda does something to impact other services I can see where that might muddy things a little. But we aren't giving it any unusual permissions to do other things mid execution, so I can't really see that coming into play.

In terms of these policies... I was just duplicating the same policies that the auto-generated roles already had, so this doesn't represent a change to permissions. (It's also what is suggested in the cdk docs if you do override this role.) However, I wasn't aware that the AWSLambdaVPCAccessExecutionRole includes write permissions to all resources. I guess that's something to keep in mind for any lambdas we have in VPCs where this may not have been considered.

I can definitely be more explicit with the permissions to only allow it to work with the relevant subnet and securitygroup. The network interfaces have randomized names so I don't think we can namespace those in any meaningful way since it may need to be able to create a new one? (I'm not too familiar with this side so I might be a little off with how this part works.)

Also, just to note, marble-blueprints isn't doing this; the front-end stacks are just using auto-created roles for lambdas, but those aren't created in a VPC so they don't have the `service-role/AWSLambdaBasicExecutionRole` managed policy.

2021-04-05 12:07 UTC, ialford commented
Yeah, I mean this has always been my issue with the way AWS handles IAM around some resources. The changes are good, but don't necessarily reduce the blast radius sufficiently - any network interface could still be impacted.

2021-04-05 12:09 UTC, ialford commented on src/aleph-gateway-stack.ts
> +                `arn:aws:ec2:${this.region}:${this.account}:security-group/${securityGroupId}`,
I'm not sure this is needed - none of the actions in the policy list `security-group` as an impacted resource type. Were you wanting to use it as a [condition key](https://docs.amazonaws.cn/en_us/service-authorization/latest/reference/list_amazonec2.html#amazonec2-ec2_Subnet)?

2021-04-05 13:07 UTC, mlkirkpatrick commented on src/aleph-gateway-stack.ts
> +                `arn:aws:ec2:${this.region}:${this.account}:security-group/${securityGroupId}`,
ec2:CreateNetworkInterface takes a security-group, although it appears to be optional. I included it since it was readily available anyway.

2021-04-05 13:09 UTC, ialford approved these changes

2021-04-05 13:11 UTC, merged